# Generated by Django 3.0.5 on 2020-05-11 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='objectCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.CharField(max_length=200)),
                ('categoryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.AdvertisementCategory')),
            ],
        ),
    ]
